### ISSUE TITLE
Sidekick bug 

### ISSUE THREAD

**Issue by ThePlatinumGhost** [TTT-2/ttt2-role_jack#2] opened 2019-12-26 19:18 UTC
**Describe the bug**
I seem to have found a problem with the jackal when he shoots someone with the sidekick deagle. The role is changed as it should be, but with certain classes (the ones that are always identified like detective, jester, pirate and so on) other players still see the previous one on the scoreboard and while looking at them.
Is that intended?

**Video**
https://www.youtube.com/watch?v=hBcAI9RiOsM

**Expected behaviour**
The detective should loses "Detective" role at the apparence

**Comment by TimGoll** [comment] 2019-12-26 19:20
Yes, this is intended. The role change shouldn't be public. Even a traitor does not see if his mate is a real T or a sidekick

Just a small hint: it's called roles, not classes

**Comment by ThePlatinumGhost** [comment] 2019-12-26 19:55
I get what you're saying but I think it can get really confusing for players. Seeing someone with a role you trusted 100% (like a detective or your own bodyguard) randomly starting to shoot at you can really throw people off.
Maybe a cvar in the future could be nice so you can decide if you want it to be public or not

**Comment by TimGoll** [comment] 2019-12-26 20:18
Showing publicly that a player is a sidekick is a bad idea imho. It's like showing you who is a traitor.
The main purpose of the new roles is to remove the "safe players" problem.

**Comment by saibotk** [comment] 2019-12-29 21:36
As this is the intended behavior, i am going to close this issue.

**Closed by saibotk** 2019-12-29 21:36 UTC

**Comment by ToFurkie** [comment] 2020-04-05 16:35
Wanted to bring up the discussion again as I recently encountered this.
I personally think any identifying icons should be removed once converted to a Sidekick. The responsibility of concealing their identities should fall on the Jackal when choosing someone to convert, rather than punishing traitors by actively misleading them that their teammate is still on their side, when they have no ability to know a Jackal is even in the game. I also want to note that icons go away, even for Detective, when converted into an infected or zombie. The same rational I feel should apply for Jackal/Sidekicks

**Comment by TimGoll** [comment] 2020-04-05 17:49
> I also want to note that icons go away, even for Detective, when converted into an infected or zombie

If this happens, this is a bug

**Comment by ThePlatinumGhost** [comment] 2020-04-06 08:42
> Wanted to bring up the discussion again as I recently encountered this.
> I personally think any identifying icons should be removed once converted to a Sidekick. The responsibility of concealing their identities should fall on the Jackal when choosing someone to convert, rather than punishing traitors by actively misleading them that their teammate is still on their side, when they have no ability to know a Jackal is even in the game.

As already mentioned, I think that a server cvar could make everyone happy, despite conflicting ideas, so everyone sets the jackal in their server at will 👍

**Comment by TimGoll** [comment] 2020-04-06 09:30
This would also mean that the traitor will be no longer shown as a traitor in the scoreboard

**Comment by ThePlatinumGhost** [comment] 2020-04-06 10:15
> This would also mean that the traitor will be no longer shown as a traitor in the scoreboard

Yes, same thing if you have a bodyguard or you work with a pirate, you would no longer see him as an ally
in the end if you implement the cvar like "" ttt_jackal_publicity" it depends on how a person prefers to put the jackal on his server
currently in the current state you cannot literally trust the detective or your bodyguard because they could be sidekick, this mechanic has created a bit of confusion in my server, but after a while I managed to explain it to my users
and also this creates a lot of fear, for me you should still keep a little bit the mechanics of the safe player so at least to have the few users you can trust
obviously this is just my opinion about it nothing against the current jackal / sidekick and I always appreciate your work 👍

**Comment by ToFurkie** [comment] 2020-04-06 10:20
Do you mean traitors will not show as traitor on the scoreboard when turned into a Sidekick, or will they not appear as traitor at all? If it's the latter, that would put a big damper on other roles, which is not ideal for anyone. I personally see the icons/leaderboard highlights as a constant meant to be concrete indications, and when those indications change, should be acted upon

With that said, if no middle ground can be found, I'd at least would prefer traitors be notified that a Jackal/Infected/Necromancer (or any 3rd party role, really) are in the current game (possibly as a convar for either the server or within each role), so they can at least be ready for a potential role change on their team

**Comment by TimGoll** [comment] 2020-04-06 10:21
> Do you mean traitors will not show as traitor on the scoreboard when turned into a Sidekick
this.

**Comment by ToFurkie** [comment] 2020-04-06 10:24
So the former then. I personally don't see it as a problem, but that is only my opinion and would be happy with that as a server wide convar for conversion roles. If this is a possibility, I'd love to even see an end screen notification (I think it's the addon for round info) where it tells everyone what role was converted into [x], though that may be too much when an entire lobby is turned to infected, or a sidekick chain kicks off

**Comment by TimGoll** [comment] 2020-04-06 10:26
Something like your idea is already planned. It should at least show the initial role and the role at round end
